name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.10.0'
          cache: 'npm'

      - name: Use specific npm version
        run: npm install -g npm@8.19.2

      - name: Install dependencies
        run: npm ci

      - name: Update browserslist db
        run: npx browserslist@latest --update-db

      - name: Build
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Create .htaccess file
        run: |
          cat > ./dist/.htaccess << 'EOF'
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{HTTPS} !=on
            RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
            RewriteBase /pl
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.html [L]
          </IfModule>
          EOF

      - name: Set release folder name
        run: echo "RELEASE_FOLDER=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Deploy to FTP (release folder)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: release/${{ env.RELEASE_FOLDER }}/

      - name: Clean public_html and deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: public_html/
          dangerous-clean-slate: true